### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by uriva** [Teemu/pytest-sugar#190]
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/_pytest/main.py", line 196, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 92, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/_pytest/runner.py", line 81, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/_pytest/runner.py", line 97, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py", line 145, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pytest_sugar.py", line 436, in pytest_runtest_logreport
INTERNALERROR>     self.insert_progress(report)
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pytest_sugar.py", line 323, in insert_progress
INTERNALERROR>     append_string = get_progress_bar()
INTERNALERROR>   File "/home/uri/project/lib/python3.7/site-packages/pytest_sugar.py", line 310, in get_progress_bar
INTERNALERROR>     progressbar += colored(bar[block],
INTERNALERROR> IndexError: string index out of range
```

**Comment by Teemu** [comment]
This doesn't contain information on how to reproduce so have to close.

**Comment by sweh** [comment]
Hi Teemu,

I have the same error sometime. Looks like this is raised when calling tests with `pytest-xdist`.

**Comment by MichaelDanielTom** [comment]
I'm also getting the same error but only when running tests that contain some type of async code (like tests that use the mark `@pytest.mark.asyncio`) with xdist like `pytest -n auto --dist loadscope`. One thing to note is that it always happens at the end of the test run, regardless of if the tests all pass or if some of them fail. Here's the complete list of pytest related dependencies I've I've been using.
```
pytest-django==4.4.0
pytest-mock==3.6.1
pytest-socket==0.4.1
pytest-asyncio==0.16.0
pytest-xdist[psutil]==2.4.0
pytest-sugar==0.9.4
```
