### ISSUE TITLE
INTERNALERROR after upgrading to Python to 3.8.2

### ISSUE THREAD

**Issue by romulo-dbts** [Teemu/pytest-sugar#193]
Hi there,

After upgrading my Python version to 3.8.2 I stated getting the following error when running my test suit. Removing pytest-sugar my test suit runs normally.

#### Command used to run py.test
````pytest my_project````

```
$ pytest my_project           
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pytest_sugar.py", line 176, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/home/romulo/venvs/my_project/lib/python3.8/site-packages/pytest_sugar.py", line 214, in __init__
INTERNALERROR>     self.writer = self._tw
INTERNALERROR> AttributeError: can't set attribute
```

Pytest.ini
```
[pytest]
DJANGO_SETTINGS_MODULE = my_project.settings
addopts = --pep8 --pyargs --cov-config my_project/.coveragerc
norecursedirs = .* build dist _darcs {arch} *.egg migrations management const forms templates

pep8maxlinelength = 99
pep8ignore =
    migrations/* ALL
    tmp/* ALL
    scripts/* ALL
    docs/* ALL
    tests/* ALL

env =
    APPLICATIONINSIGHTS_INSTRUMENTATION_KEY=
```

Requirements
```
amqp==2.5.2
anyjson==0.3.3
apipkg==1.5
applicationinsights==0.11.9
argh==0.26.2
asgiref==3.2.7
atomicwrites==1.3.0
attrs==19.3.0
backoff==1.10.0
billiard==3.6.3.0
cachetools==4.0.0
celery==4.4.2
certifi==2020.4.5.1
chardet==3.0.4
colorama==0.4.3
coverage==5.0.4
Django==3.0.5
django-mysql==3.3.0
django-redis==4.11.0
django-waffle==0.20.0
docopt==0.4.0
execnet==1.7.1
flower==0.9.4
google-api-core==1.16.0
google-auth==1.13.1
googleapis-common-protos==1.51.0
humanize==0.5.1
idna==2.9
importlib-metadata==1.6.0
kombu==4.6.8
mandrill==1.0.59
mock==4.0.2
more-itertools==8.2.0
mysqlclient==1.4.6
opencensus==0.7.7
opencensus-context==0.1.1
opencensus-ext-azure==1.0.2
packaging==20.3
pathtools==0.1.2
pep8==1.7.1
pluggy==0.13.1
protobuf==3.11.3
psutil==5.7.0
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
pytest==5.4.1
pytest-cache==1.0
pytest-cov==2.8.1
pytest-django==3.9.0
pytest-env==0.6.2
pytest-pep8==1.0.6
pytest-responses==0.4.0
pytest-sugar==0.9.2
pytest-watch==4.2.0
python-decouple==3.3
pytz==2019.3
PyYAML==5.3.1
redis==3.4.1
requests==2.23.0
responses==0.10.12
rsa==4.0
schematics==2.1.0
sentry-sdk==0.14.3
six==1.14.0
sqlparse==0.3.1
termcolor==1.1.0
tornado==6.0.4
urllib3==1.25.8
vine==1.3.0
watchdog==0.10.2
wcwidth==0.1.9
zipp==3.1.0
```

**Comment by RonnyPfannschmidt** [comment]
this is a known issue in combination with pytest 5.4.x that will be fixed in pytest 5.4.2

**Comment by romulo-dbts** [comment]
Hi @RonnyPfannschmidt thank you for replying me so quick and letting me know about the plans for fixing it.

**Comment by RonnyPfannschmidt** [comment]
Im on mobile so i can't crosslink the related issues on this tracker

**Comment by romulo-dbts** [comment]
@RonnyPfannschmidt I believe that you are talking about this one https://github.com/Teemu/pytest-sugar/issues/187, right?

**Comment by RonnyPfannschmidt** [comment]
Exactly, thank you

**Comment by Ambro17** [comment]
Just came here to say i experienced the same bug with `python 3.7` and `pytest-sugar==0.9.2`

**Comment by Teemu** [comment]
I think this has been fixed right?
